# Generated by Django 5.2.1 on 2025-05-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.CharField()),
                ('shortened_code', models.CharField()),
                ('times_used', models.IntegerField(default=0)),
            ],
        ),
    ]
