# Generated by Django 5.2.1 on 2025-06-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_url_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='a',
        ),
    ]
